.class public Llecho/lib/hellocharts/model/Axis;
.super Ljava/lang/Object;
.source "Axis.java"


# static fields
.field public static final DEFAULT_MAX_AXIS_LABEL_CHARS:I = 0x4

.field public static final DEFAULT_TEXT_SIZE_SP:I = 0xc


# instance fields
.field private formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

.field private hasLines:Z

.field private hasSeparationLine:Z

.field private hasThumb:Z

.field private hasTiltedLabels:Z

.field private isAutoGenerated:Z

.field private isInside:Z

.field private lineColor:I

.field private maxLabelChars:I

.field private name:Ljava/lang/String;

.field private textColor:I

.field private textSize:I

.field private typeface:Landroid/graphics/Typeface;

.field private values:Ljava/util/List;
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "Ljava/util/List",
            "<",
            "Llecho/lib/hellocharts/model/AxisValue;",
            ">;"
        }
    .end annotation
.end field


# direct methods
.method public constructor <init>()V
    .locals 3

    .prologue
    const/4 v2, 0x1

    const/4 v1, 0x0

    .line 88
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 26
    const/16 v0, 0xc

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->textSize:I

    .line 34
    const/4 v0, 0x4

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    .line 38
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    .line 46
    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    .line 50
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    .line 54
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    .line 58
    const v0, -0x333334

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->textColor:I

    .line 62
    sget v0, Llecho/lib/hellocharts/util/ChartUtils;->DEFAULT_DARKEN_COLOR:I

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    .line 71
    new-instance v0, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;

    invoke-direct {v0}, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;-><init>()V

    iput-object v0, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    .line 76
    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    .line 78
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->hasTiltedLabels:Z

    .line 83
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    .line 89
    return-void
.end method

.method public constructor <init>(Ljava/util/List;)V
    .locals 3
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List",
            "<",
            "Llecho/lib/hellocharts/model/AxisValue;",
            ">;)V"
        }
    .end annotation

    .prologue
    .local p1, values:Ljava/util/List;,"Ljava/util/List<Llecho/lib/hellocharts/model/AxisValue;>;"
    const/4 v2, 0x1

    const/4 v1, 0x0

    .line 94
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 26
    const/16 v0, 0xc

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->textSize:I

    .line 34
    const/4 v0, 0x4

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    .line 38
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    .line 46
    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    .line 50
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    .line 54
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    .line 58
    const v0, -0x333334

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->textColor:I

    .line 62
    sget v0, Llecho/lib/hellocharts/util/ChartUtils;->DEFAULT_DARKEN_COLOR:I

    iput v0, p0, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    .line 71
    new-instance v0, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;

    invoke-direct {v0}, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;-><init>()V

    iput-object v0, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    .line 76
    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    .line 78
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->hasTiltedLabels:Z

    .line 83
    iput-boolean v1, p0, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    .line 95
    invoke-virtual {p0, p1}, Llecho/lib/hellocharts/model/Axis;->setValues(Ljava/util/List;)Llecho/lib/hellocharts/model/Axis;

    .line 96
    return-void
.end method

.method public constructor <init>(Llecho/lib/hellocharts/model/Axis;)V
    .locals 5
    .parameter "axis"

    .prologue
    const/4 v4, 0x1

    const/4 v3, 0x0

    .line 98
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 26
    const/16 v2, 0xc

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->textSize:I

    .line 34
    const/4 v2, 0x4

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    .line 38
    new-instance v2, Ljava/util/ArrayList;

    invoke-direct {v2}, Ljava/util/ArrayList;-><init>()V

    iput-object v2, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    .line 46
    iput-boolean v4, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    .line 50
    iput-boolean v3, p0, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    .line 54
    iput-boolean v3, p0, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    .line 58
    const v2, -0x333334

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->textColor:I

    .line 62
    sget v2, Llecho/lib/hellocharts/util/ChartUtils;->DEFAULT_DARKEN_COLOR:I

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    .line 71
    new-instance v2, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;

    invoke-direct {v2}, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;-><init>()V

    iput-object v2, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    .line 76
    iput-boolean v4, p0, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    .line 78
    iput-boolean v3, p0, Llecho/lib/hellocharts/model/Axis;->hasTiltedLabels:Z

    .line 83
    iput-boolean v3, p0, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    .line 99
    iget-object v2, p1, Llecho/lib/hellocharts/model/Axis;->name:Ljava/lang/String;

    iput-object v2, p0, Llecho/lib/hellocharts/model/Axis;->name:Ljava/lang/String;

    .line 100
    iget-boolean v2, p1, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    .line 101
    iget-boolean v2, p1, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    .line 102
    iget-boolean v2, p1, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    .line 103
    iget v2, p1, Llecho/lib/hellocharts/model/Axis;->textColor:I

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->textColor:I

    .line 104
    iget v2, p1, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    .line 105
    iget v2, p1, Llecho/lib/hellocharts/model/Axis;->textSize:I

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->textSize:I

    .line 106
    iget v2, p1, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    iput v2, p0, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    .line 107
    iget-object v2, p1, Llecho/lib/hellocharts/model/Axis;->typeface:Landroid/graphics/Typeface;

    iput-object v2, p0, Llecho/lib/hellocharts/model/Axis;->typeface:Landroid/graphics/Typeface;

    .line 108
    iget-object v2, p1, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    iput-object v2, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    .line 109
    iget-boolean v2, p1, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    .line 110
    iget-boolean v2, p1, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    iput-boolean v2, p0, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    .line 112
    iget-object v2, p1, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    invoke-interface {v2}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v1

    .local v1, i$:Ljava/util/Iterator;
    :goto_0
    invoke-interface {v1}, Ljava/util/Iterator;->hasNext()Z

    move-result v2

    if-eqz v2, :cond_0

    invoke-interface {v1}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v0

    check-cast v0, Llecho/lib/hellocharts/model/AxisValue;

    .line 113
    .local v0, axisValue:Llecho/lib/hellocharts/model/AxisValue;
    iget-object v2, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    new-instance v3, Llecho/lib/hellocharts/model/AxisValue;

    invoke-direct {v3, v0}, Llecho/lib/hellocharts/model/AxisValue;-><init>(Llecho/lib/hellocharts/model/AxisValue;)V

    invoke-interface {v2, v3}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    goto :goto_0

    .line 115
    .end local v0           #axisValue:Llecho/lib/hellocharts/model/AxisValue;
    :cond_0
    return-void
.end method

.method public static generateAxisFromCollection(Ljava/util/List;)Llecho/lib/hellocharts/model/Axis;
    .locals 7
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List",
            "<",
            "Ljava/lang/Float;",
            ">;)",
            "Llecho/lib/hellocharts/model/Axis;"
        }
    .end annotation

    .prologue
    .line 136
    .local p0, axisValues:Ljava/util/List;,"Ljava/util/List<Ljava/lang/Float;>;"
    new-instance v5, Ljava/util/ArrayList;

    invoke-direct {v5}, Ljava/util/ArrayList;-><init>()V

    .line 137
    .local v5, values:Ljava/util/List;,"Ljava/util/List<Llecho/lib/hellocharts/model/AxisValue;>;"
    const/4 v3, 0x0

    .line 138
    .local v3, index:I
    invoke-interface {p0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v2

    .local v2, i$:Ljava/util/Iterator;
    :goto_0
    invoke-interface {v2}, Ljava/util/Iterator;->hasNext()Z

    move-result v6

    if-eqz v6, :cond_0

    invoke-interface {v2}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v6

    check-cast v6, Ljava/lang/Float;

    invoke-virtual {v6}, Ljava/lang/Float;->floatValue()F

    move-result v4

    .line 139
    .local v4, value:F
    new-instance v1, Llecho/lib/hellocharts/model/AxisValue;

    invoke-direct {v1, v4}, Llecho/lib/hellocharts/model/AxisValue;-><init>(F)V

    .line 140
    .local v1, axisValue:Llecho/lib/hellocharts/model/AxisValue;
    invoke-interface {v5, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 141
    add-int/lit8 v3, v3, 0x1

    .line 142
    goto :goto_0

    .line 144
    .end local v1           #axisValue:Llecho/lib/hellocharts/model/AxisValue;
    .end local v4           #value:F
    :cond_0
    new-instance v0, Llecho/lib/hellocharts/model/Axis;

    invoke-direct {v0, v5}, Llecho/lib/hellocharts/model/Axis;-><init>(Ljava/util/List;)V

    .line 145
    .local v0, axis:Llecho/lib/hellocharts/model/Axis;
    return-object v0
.end method

.method public static generateAxisFromCollection(Ljava/util/List;Ljava/util/List;)Llecho/lib/hellocharts/model/Axis;
    .locals 8
    .parameter
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List",
            "<",
            "Ljava/lang/Float;",
            ">;",
            "Ljava/util/List",
            "<",
            "Ljava/lang/String;",
            ">;)",
            "Llecho/lib/hellocharts/model/Axis;"
        }
    .end annotation

    .prologue
    .line 152
    .local p0, axisValues:Ljava/util/List;,"Ljava/util/List<Ljava/lang/Float;>;"
    .local p1, axisValuesLabels:Ljava/util/List;,"Ljava/util/List<Ljava/lang/String;>;"
    invoke-interface {p0}, Ljava/util/List;->size()I

    move-result v6

    invoke-interface {p1}, Ljava/util/List;->size()I

    move-result v7

    if-eq v6, v7, :cond_0

    .line 153
    new-instance v6, Ljava/lang/IllegalArgumentException;

    const-string v7, "Values and labels lists must have the same size!"

    invoke-direct {v6, v7}, Ljava/lang/IllegalArgumentException;-><init>(Ljava/lang/String;)V

    throw v6

    .line 156
    :cond_0
    new-instance v5, Ljava/util/ArrayList;

    invoke-direct {v5}, Ljava/util/ArrayList;-><init>()V

    .line 157
    .local v5, values:Ljava/util/List;,"Ljava/util/List<Llecho/lib/hellocharts/model/AxisValue;>;"
    const/4 v3, 0x0

    .line 158
    .local v3, index:I
    invoke-interface {p0}, Ljava/util/List;->iterator()Ljava/util/Iterator;

    move-result-object v2

    .local v2, i$:Ljava/util/Iterator;
    :goto_0
    invoke-interface {v2}, Ljava/util/Iterator;->hasNext()Z

    move-result v6

    if-eqz v6, :cond_1

    invoke-interface {v2}, Ljava/util/Iterator;->next()Ljava/lang/Object;

    move-result-object v6

    check-cast v6, Ljava/lang/Float;

    invoke-virtual {v6}, Ljava/lang/Float;->floatValue()F

    move-result v4

    .line 159
    .local v4, value:F
    new-instance v7, Llecho/lib/hellocharts/model/AxisValue;

    invoke-direct {v7, v4}, Llecho/lib/hellocharts/model/AxisValue;-><init>(F)V

    invoke-interface {p1, v3}, Ljava/util/List;->get(I)Ljava/lang/Object;

    move-result-object v6

    check-cast v6, Ljava/lang/String;

    invoke-virtual {v7, v6}, Llecho/lib/hellocharts/model/AxisValue;->setLabel(Ljava/lang/String;)Llecho/lib/hellocharts/model/AxisValue;

    move-result-object v1

    .line 160
    .local v1, axisValue:Llecho/lib/hellocharts/model/AxisValue;
    invoke-interface {v5, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 161
    add-int/lit8 v3, v3, 0x1

    .line 162
    goto :goto_0

    .line 164
    .end local v1           #axisValue:Llecho/lib/hellocharts/model/AxisValue;
    .end local v4           #value:F
    :cond_1
    new-instance v0, Llecho/lib/hellocharts/model/Axis;

    invoke-direct {v0, v5}, Llecho/lib/hellocharts/model/Axis;-><init>(Ljava/util/List;)V

    .line 165
    .local v0, axis:Llecho/lib/hellocharts/model/Axis;
    return-object v0
.end method

.method public static generateAxisFromRange(FFF)Llecho/lib/hellocharts/model/Axis;
    .locals 5
    .parameter "start"
    .parameter "stop"
    .parameter "step"

    .prologue
    .line 122
    new-instance v3, Ljava/util/ArrayList;

    invoke-direct {v3}, Ljava/util/ArrayList;-><init>()V

    .line 123
    .local v3, values:Ljava/util/List;,"Ljava/util/List<Llecho/lib/hellocharts/model/AxisValue;>;"
    move v2, p0

    .local v2, value:F
    :goto_0
    cmpg-float v4, v2, p1

    if-gtz v4, :cond_0

    .line 124
    new-instance v1, Llecho/lib/hellocharts/model/AxisValue;

    invoke-direct {v1, v2}, Llecho/lib/hellocharts/model/AxisValue;-><init>(F)V

    .line 125
    .local v1, axisValue:Llecho/lib/hellocharts/model/AxisValue;
    invoke-interface {v3, v1}, Ljava/util/List;->add(Ljava/lang/Object;)Z

    .line 123
    add-float/2addr v2, p2

    goto :goto_0

    .line 128
    .end local v1           #axisValue:Llecho/lib/hellocharts/model/AxisValue;
    :cond_0
    new-instance v0, Llecho/lib/hellocharts/model/Axis;

    invoke-direct {v0, v3}, Llecho/lib/hellocharts/model/Axis;-><init>(Ljava/util/List;)V

    .line 129
    .local v0, axis:Llecho/lib/hellocharts/model/Axis;
    return-object v0
.end method


# virtual methods
.method public getFormatter()Llecho/lib/hellocharts/formatter/AxisValueFormatter;
    .locals 1

    .prologue
    .line 280
    iget-object v0, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    return-object v0
.end method

.method public getLineColor()I
    .locals 1

    .prologue
    .line 236
    iget v0, p0, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    return v0
.end method

.method public getMaxLabelChars()I
    .locals 1

    .prologue
    .line 254
    iget v0, p0, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    return v0
.end method

.method public getName()Ljava/lang/String;
    .locals 1

    .prologue
    .line 184
    iget-object v0, p0, Llecho/lib/hellocharts/model/Axis;->name:Ljava/lang/String;

    return-object v0
.end method

.method public getTextColor()I
    .locals 1

    .prologue
    .line 211
    iget v0, p0, Llecho/lib/hellocharts/model/Axis;->textColor:I

    return v0
.end method

.method public getTextSize()I
    .locals 1

    .prologue
    .line 245
    iget v0, p0, Llecho/lib/hellocharts/model/Axis;->textSize:I

    return v0
.end method

.method public getTypeface()Landroid/graphics/Typeface;
    .locals 1

    .prologue
    .line 271
    iget-object v0, p0, Llecho/lib/hellocharts/model/Axis;->typeface:Landroid/graphics/Typeface;

    return-object v0
.end method

.method public getValues()Ljava/util/List;
    .locals 1
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "()",
            "Ljava/util/List",
            "<",
            "Llecho/lib/hellocharts/model/AxisValue;",
            ">;"
        }
    .end annotation

    .prologue
    .line 169
    iget-object v0, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    return-object v0
.end method

.method public hasLines()Z
    .locals 1

    .prologue
    .line 202
    iget-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    return v0
.end method

.method public hasSeparationLine()Z
    .locals 1

    .prologue
    .line 301
    iget-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    return v0
.end method

.method public hasTiltedLabels()Z
    .locals 1

    .prologue
    .line 305
    iget-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->hasTiltedLabels:Z

    return v0
.end method

.method public isAutoGenerated()Z
    .locals 1

    .prologue
    .line 193
    iget-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    return v0
.end method

.method public isHasThumb()Z
    .locals 1

    .prologue
    .line 314
    iget-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    return v0
.end method

.method public isInside()Z
    .locals 1

    .prologue
    .line 223
    iget-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    return v0
.end method

.method public setAutoGenerated(Z)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "isAutoGenerated"

    .prologue
    .line 197
    iput-boolean p1, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    .line 198
    return-object p0
.end method

.method public setFormatter(Llecho/lib/hellocharts/formatter/AxisValueFormatter;)Llecho/lib/hellocharts/model/Axis;
    .locals 1
    .parameter "formatter"

    .prologue
    .line 284
    if-nez p1, :cond_0

    .line 285
    new-instance v0, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;

    invoke-direct {v0}, Llecho/lib/hellocharts/formatter/SimpleAxisValueFormatter;-><init>()V

    iput-object v0, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    .line 289
    :goto_0
    return-object p0

    .line 287
    :cond_0
    iput-object p1, p0, Llecho/lib/hellocharts/model/Axis;->formatter:Llecho/lib/hellocharts/formatter/AxisValueFormatter;

    goto :goto_0
.end method

.method public setHasLines(Z)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "hasLines"

    .prologue
    .line 206
    iput-boolean p1, p0, Llecho/lib/hellocharts/model/Axis;->hasLines:Z

    .line 207
    return-object p0
.end method

.method public setHasSeparationLine(Z)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "hasSeparationLine"

    .prologue
    .line 296
    iput-boolean p1, p0, Llecho/lib/hellocharts/model/Axis;->hasSeparationLine:Z

    .line 297
    return-object p0
.end method

.method public setHasThumb(Z)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "hasThumb"

    .prologue
    .line 318
    iput-boolean p1, p0, Llecho/lib/hellocharts/model/Axis;->hasThumb:Z

    .line 319
    return-object p0
.end method

.method public setHasTiltedLabels(Z)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "hasTiltedLabels"

    .prologue
    .line 309
    iput-boolean p1, p0, Llecho/lib/hellocharts/model/Axis;->hasTiltedLabels:Z

    .line 310
    return-object p0
.end method

.method public setInside(Z)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "isInside"

    .prologue
    .line 231
    iput-boolean p1, p0, Llecho/lib/hellocharts/model/Axis;->isInside:Z

    .line 232
    return-object p0
.end method

.method public setLineColor(I)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "lineColor"

    .prologue
    .line 240
    iput p1, p0, Llecho/lib/hellocharts/model/Axis;->lineColor:I

    .line 241
    return-object p0
.end method

.method public setMaxLabelChars(I)Llecho/lib/hellocharts/model/Axis;
    .locals 1
    .parameter "maxLabelChars"

    .prologue
    .line 261
    if-gez p1, :cond_1

    .line 262
    const/4 p1, 0x0

    .line 266
    :cond_0
    :goto_0
    iput p1, p0, Llecho/lib/hellocharts/model/Axis;->maxLabelChars:I

    .line 267
    return-object p0

    .line 263
    :cond_1
    const/16 v0, 0x20

    if-le p1, v0, :cond_0

    .line 264
    const/16 p1, 0x20

    goto :goto_0
.end method

.method public setName(Ljava/lang/String;)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "name"

    .prologue
    .line 188
    iput-object p1, p0, Llecho/lib/hellocharts/model/Axis;->name:Ljava/lang/String;

    .line 189
    return-object p0
.end method

.method public setTextColor(I)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "color"

    .prologue
    .line 215
    iput p1, p0, Llecho/lib/hellocharts/model/Axis;->textColor:I

    .line 216
    return-object p0
.end method

.method public setTextSize(I)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "textSize"

    .prologue
    .line 249
    iput p1, p0, Llecho/lib/hellocharts/model/Axis;->textSize:I

    .line 250
    return-object p0
.end method

.method public setTypeface(Landroid/graphics/Typeface;)Llecho/lib/hellocharts/model/Axis;
    .locals 0
    .parameter "typeface"

    .prologue
    .line 275
    iput-object p1, p0, Llecho/lib/hellocharts/model/Axis;->typeface:Landroid/graphics/Typeface;

    .line 276
    return-object p0
.end method

.method public setValues(Ljava/util/List;)Llecho/lib/hellocharts/model/Axis;
    .locals 1
    .parameter
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "(",
            "Ljava/util/List",
            "<",
            "Llecho/lib/hellocharts/model/AxisValue;",
            ">;)",
            "Llecho/lib/hellocharts/model/Axis;"
        }
    .end annotation

    .prologue
    .line 173
    .local p1, values:Ljava/util/List;,"Ljava/util/List<Llecho/lib/hellocharts/model/AxisValue;>;"
    if-nez p1, :cond_0

    .line 174
    new-instance v0, Ljava/util/ArrayList;

    invoke-direct {v0}, Ljava/util/ArrayList;-><init>()V

    iput-object v0, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    .line 179
    :goto_0
    const/4 v0, 0x0

    iput-boolean v0, p0, Llecho/lib/hellocharts/model/Axis;->isAutoGenerated:Z

    .line 180
    return-object p0

    .line 176
    :cond_0
    iput-object p1, p0, Llecho/lib/hellocharts/model/Axis;->values:Ljava/util/List;

    goto :goto_0
.end method
