.class public Llecho/lib/hellocharts/util/FloatUtils;
.super Ljava/lang/Object;
.source "FloatUtils.java"


# static fields
.field public static final POW10:[I


# direct methods
.method static constructor <clinit>()V
    .locals 1

    .prologue
    .line 4
    const/4 v0, 0x7

    new-array v0, v0, [I

    fill-array-data v0, :array_0

    sput-object v0, Llecho/lib/hellocharts/util/FloatUtils;->POW10:[I

    return-void

    nop

    :array_0
    .array-data 0x4
        0x1t 0x0t 0x0t 0x0t
        0xat 0x0t 0x0t 0x0t
        0x64t 0x0t 0x0t 0x0t
        0xe8t 0x3t 0x0t 0x0t
        0x10t 0x27t 0x0t 0x0t
        0xa0t 0x86t 0x1t 0x0t
        0x40t 0x42t 0xft 0x0t
    .end array-data
.end method

.method public constructor <init>()V
    .locals 0

    .prologue
    .line 3
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method

.method public static almostEqual(FFFF)Z
    .locals 4
    .parameter "a"
    .parameter "b"
    .parameter "absoluteDiff"
    .parameter "relativeDiff"

    .prologue
    const/4 v2, 0x1

    .line 64
    sub-float v3, p0, p1

    invoke-static {v3}, Ljava/lang/Math;->abs(F)F

    move-result v0

    .line 65
    .local v0, diff:F
    cmpg-float v3, v0, p2

    if-gtz v3, :cond_1

    .line 77
    :cond_0
    :goto_0
    return v2

    .line 69
    :cond_1
    invoke-static {p0}, Ljava/lang/Math;->abs(F)F

    move-result p0

    .line 70
    invoke-static {p1}, Ljava/lang/Math;->abs(F)F

    move-result p1

    .line 71
    cmpl-float v3, p0, p1

    if-lez v3, :cond_2

    move v1, p0

    .line 73
    .local v1, largest:F
    :goto_1
    mul-float v3, v1, p3

    cmpg-float v3, v0, v3

    if-lez v3, :cond_0

    .line 77
    const/4 v2, 0x0

    goto :goto_0

    .end local v1           #largest:F
    :cond_2
    move v1, p1

    .line 71
    goto :goto_1
.end method

.method public static computeAutoGeneratedAxisValues(FFILlecho/lib/hellocharts/util/AxisAutoValues;)V
    .locals 24
    .parameter "start"
    .parameter "stop"
    .parameter "steps"
    .parameter "outValues"

    .prologue
    .line 153
    sub-float v19, p1, p0

    move/from16 v0, v19

    float-to-double v14, v0

    .line 154
    .local v14, range:D
    if-eqz p2, :cond_0

    const-wide/16 v20, 0x0

    cmpg-double v19, v14, v20

    if-gtz v19, :cond_1

    .line 155
    :cond_0
    const/16 v19, 0x0

    move/from16 v0, v19

    new-array v0, v0, [F

    move-object/from16 v19, v0

    move-object/from16 v0, v19

    move-object/from16 v1, p3

    iput-object v0, v1, Llecho/lib/hellocharts/util/AxisAutoValues;->values:[F

    .line 156
    const/16 v19, 0x0

    move/from16 v0, v19

    move-object/from16 v1, p3

    iput v0, v1, Llecho/lib/hellocharts/util/AxisAutoValues;->valuesNumber:I

    .line 195
    :goto_0
    return-void

    .line 160
    :cond_1
    move/from16 v0, p2

    int-to-double v0, v0

    move-wide/from16 v20, v0

    div-double v16, v14, v20

    .line 161
    .local v16, rawInterval:D
    invoke-static/range {v16 .. v17}, Llecho/lib/hellocharts/util/FloatUtils;->roundToOneSignificantFigure(D)F

    move-result v19

    move/from16 v0, v19

    float-to-double v4, v0

    .line 162
    .local v4, interval:D
    const-wide/high16 v20, 0x4024

    invoke-static {v4, v5}, Ljava/lang/Math;->log10(D)D

    move-result-wide v22

    move-wide/from16 v0, v22

    double-to-int v0, v0

    move/from16 v19, v0

    move/from16 v0, v19

    int-to-double v0, v0

    move-wide/from16 v22, v0

    invoke-static/range {v20 .. v23}, Ljava/lang/Math;->pow(DD)D

    move-result-wide v6

    .line 163
    .local v6, intervalMagnitude:D
    div-double v20, v4, v6

    move-wide/from16 v0, v20

    double-to-int v8, v0

    .line 164
    .local v8, intervalSigDigit:I
    const/16 v19, 0x5

    move/from16 v0, v19

    if-le v8, v0, :cond_2

    .line 166
    const-wide/high16 v20, 0x4024

    mul-double v20, v20, v6

    invoke-static/range {v20 .. v21}, Ljava/lang/Math;->floor(D)D

    move-result-wide v4

    .line 169
    :cond_2
    move/from16 v0, p0

    float-to-double v0, v0

    move-wide/from16 v20, v0

    div-double v20, v20, v4

    invoke-static/range {v20 .. v21}, Ljava/lang/Math;->ceil(D)D

    move-result-wide v20

    mul-double v2, v20, v4

    .line 170
    .local v2, first:D
    move/from16 v0, p1

    float-to-double v0, v0

    move-wide/from16 v20, v0

    div-double v20, v20, v4

    invoke-static/range {v20 .. v21}, Ljava/lang/Math;->floor(D)D

    move-result-wide v20

    mul-double v20, v20, v4

    invoke-static/range {v20 .. v21}, Llecho/lib/hellocharts/util/FloatUtils;->nextUp(D)D

    move-result-wide v12

    .line 174
    .local v12, last:D
    const/16 v18, 0x0

    .line 175
    .local v18, valuesNum:I
    move-wide v10, v2

    .local v10, intervalValue:D
    :goto_1
    cmpg-double v19, v10, v12

    if-gtz v19, :cond_3

    .line 176
    add-int/lit8 v18, v18, 0x1

    .line 175
    add-double/2addr v10, v4

    goto :goto_1

    .line 179
    :cond_3
    move/from16 v0, v18

    move-object/from16 v1, p3

    iput v0, v1, Llecho/lib/hellocharts/util/AxisAutoValues;->valuesNumber:I

    .line 181
    move-object/from16 v0, p3

    iget-object v0, v0, Llecho/lib/hellocharts/util/AxisAutoValues;->values:[F

    move-object/from16 v19, v0

    move-object/from16 v0, v19

    array-length v0, v0

    move/from16 v19, v0

    move/from16 v0, v19

    move/from16 v1, v18

    if-ge v0, v1, :cond_4

    .line 183
    move/from16 v0, v18

    new-array v0, v0, [F

    move-object/from16 v19, v0

    move-object/from16 v0, v19

    move-object/from16 v1, p3

    iput-object v0, v1, Llecho/lib/hellocharts/util/AxisAutoValues;->values:[F

    .line 186
    :cond_4
    move-wide v10, v2

    const/4 v9, 0x0

    .local v9, valueIndex:I
    :goto_2
    move/from16 v0, v18

    if-ge v9, v0, :cond_5

    .line 187
    move-object/from16 v0, p3

    iget-object v0, v0, Llecho/lib/hellocharts/util/AxisAutoValues;->values:[F

    move-object/from16 v19, v0

    double-to-float v0, v10

    move/from16 v20, v0

    aput v20, v19, v9

    .line 186
    add-double/2addr v10, v4

    add-int/lit8 v9, v9, 0x1

    goto :goto_2

    .line 190
    :cond_5
    const-wide/high16 v20, 0x3ff0

    cmpg-double v19, v4, v20

    if-gez v19, :cond_6

    .line 191
    invoke-static {v4, v5}, Ljava/lang/Math;->log10(D)D

    move-result-wide v20

    move-wide/from16 v0, v20

    neg-double v0, v0

    move-wide/from16 v20, v0

    invoke-static/range {v20 .. v21}, Ljava/lang/Math;->ceil(D)D

    move-result-wide v20

    move-wide/from16 v0, v20

    double-to-int v0, v0

    move/from16 v19, v0

    move/from16 v0, v19

    move-object/from16 v1, p3

    iput v0, v1, Llecho/lib/hellocharts/util/AxisAutoValues;->decimals:I

    goto/16 :goto_0

    .line 193
    :cond_6
    const/16 v19, 0x0

    move/from16 v0, v19

    move-object/from16 v1, p3

    iput v0, v1, Llecho/lib/hellocharts/util/AxisAutoValues;->decimals:I

    goto/16 :goto_0
.end method

.method public static formatFloat([CFIIC)I
    .locals 10
    .parameter "formattedValue"
    .parameter "value"
    .parameter "endIndex"
    .parameter "digits"
    .parameter "separator"

    .prologue
    .line 100
    sget-object v7, Llecho/lib/hellocharts/util/FloatUtils;->POW10:[I

    array-length v7, v7

    if-lt p3, v7, :cond_0

    .line 101
    add-int/lit8 v7, p2, -0x1

    const/16 v8, 0x2e

    aput-char v8, p0, v7

    .line 102
    const/4 v0, 0x1

    .line 138
    :goto_0
    return v0

    .line 104
    :cond_0
    const/4 v6, 0x0

    .line 105
    .local v6, negative:Z
    const/4 v7, 0x0

    cmpl-float v7, p1, v7

    if-nez v7, :cond_1

    .line 106
    add-int/lit8 v7, p2, -0x1

    const/16 v8, 0x30

    aput-char v8, p0, v7

    .line 107
    const/4 v0, 0x1

    goto :goto_0

    .line 109
    :cond_1
    const/4 v7, 0x0

    cmpg-float v7, p1, v7

    if-gez v7, :cond_2

    .line 110
    const/4 v6, 0x1

    .line 111
    neg-float p1, p1

    .line 113
    :cond_2
    sget-object v7, Llecho/lib/hellocharts/util/FloatUtils;->POW10:[I

    array-length v7, v7

    if-le p3, v7, :cond_3

    .line 114
    sget-object v7, Llecho/lib/hellocharts/util/FloatUtils;->POW10:[I

    array-length v7, v7

    add-int/lit8 p3, v7, -0x1

    .line 116
    :cond_3
    sget-object v7, Llecho/lib/hellocharts/util/FloatUtils;->POW10:[I

    aget v7, v7, p3

    int-to-float v7, v7

    mul-float/2addr p1, v7

    .line 117
    invoke-static {p1}, Ljava/lang/Math;->round(F)I

    move-result v7

    int-to-long v4, v7

    .line 118
    .local v4, lval:J
    add-int/lit8 v2, p2, -0x1

    .line 119
    .local v2, index:I
    const/4 v0, 0x0

    .local v0, charsNumber:I
    move v3, v2

    .line 120
    .end local v2           #index:I
    .local v3, index:I
    :goto_1
    const-wide/16 v8, 0x0

    cmp-long v7, v4, v8

    if-nez v7, :cond_4

    add-int/lit8 v7, p3, 0x1

    if-ge v0, v7, :cond_6

    .line 121
    :cond_4
    const-wide/16 v8, 0xa

    rem-long v8, v4, v8

    long-to-int v1, v8

    .line 122
    .local v1, digit:I
    const-wide/16 v8, 0xa

    div-long/2addr v4, v8

    .line 123
    add-int/lit8 v2, v3, -0x1

    .end local v3           #index:I
    .restart local v2       #index:I
    add-int/lit8 v7, v1, 0x30

    int-to-char v7, v7

    aput-char v7, p0, v3

    .line 124
    add-int/lit8 v0, v0, 0x1

    .line 125
    if-ne v0, p3, :cond_5

    .line 126
    add-int/lit8 v3, v2, -0x1

    .end local v2           #index:I
    .restart local v3       #index:I
    aput-char p4, p0, v2

    .line 127
    add-int/lit8 v0, v0, 0x1

    move v2, v3

    .end local v3           #index:I
    .restart local v2       #index:I
    :cond_5
    move v3, v2

    .line 129
    .end local v2           #index:I
    .restart local v3       #index:I
    goto :goto_1

    .line 130
    .end local v1           #digit:I
    :cond_6
    add-int/lit8 v7, v3, 0x1

    aget-char v7, p0, v7

    if-ne v7, p4, :cond_7

    .line 131
    add-int/lit8 v2, v3, -0x1

    .end local v3           #index:I
    .restart local v2       #index:I
    const/16 v7, 0x30

    aput-char v7, p0, v3

    .line 132
    add-int/lit8 v0, v0, 0x1

    move v3, v2

    .line 134
    .end local v2           #index:I
    .restart local v3       #index:I
    :cond_7
    if-eqz v6, :cond_8

    .line 135
    add-int/lit8 v2, v3, -0x1

    .end local v3           #index:I
    .restart local v2       #index:I
    const/16 v7, 0x2d

    aput-char v7, p0, v3

    .line 136
    add-int/lit8 v0, v0, 0x1

    goto :goto_0

    .end local v2           #index:I
    .restart local v3       #index:I
    :cond_8
    move v2, v3

    .end local v3           #index:I
    .restart local v2       #index:I
    goto :goto_0
.end method

.method public static nextDown(D)D
    .locals 6
    .parameter "d"

    .prologue
    const-wide/16 v4, 0x0

    .line 49
    invoke-static {p0, p1}, Ljava/lang/Double;->isNaN(D)Z

    move-result v0

    if-nez v0, :cond_0

    const-wide/high16 v0, -0x10

    cmpl-double v0, p0, v0

    if-nez v0, :cond_1

    .line 55
    .end local p0
    :cond_0
    :goto_0
    return-wide p0

    .line 52
    .restart local p0
    :cond_1
    cmpl-double v0, p0, v4

    if-nez v0, :cond_2

    .line 53
    const-wide/high16 p0, -0x4960

    goto :goto_0

    .line 55
    :cond_2
    invoke-static {p0, p1}, Ljava/lang/Double;->doubleToRawLongBits(D)J

    move-result-wide v2

    cmpl-double v0, p0, v4

    if-lez v0, :cond_3

    const/4 v0, -0x1

    :goto_1
    int-to-long v0, v0

    add-long/2addr v0, v2

    invoke-static {v0, v1}, Ljava/lang/Double;->longBitsToDouble(J)D

    move-result-wide p0

    goto :goto_0

    :cond_3
    const/4 v0, 0x1

    goto :goto_1
.end method

.method public static nextDownF(F)F
    .locals 3
    .parameter "f"

    .prologue
    const/4 v2, 0x0

    .line 22
    invoke-static {p0}, Ljava/lang/Float;->isNaN(F)Z

    move-result v0

    if-nez v0, :cond_0

    const/high16 v0, -0x80

    cmpl-float v0, p0, v0

    if-nez v0, :cond_1

    .line 28
    .end local p0
    :cond_0
    :goto_0
    return p0

    .line 25
    .restart local p0
    :cond_1
    cmpl-float v0, p0, v2

    if-nez v0, :cond_2

    .line 26
    const p0, -0x7fffffff

    goto :goto_0

    .line 28
    :cond_2
    invoke-static {p0}, Ljava/lang/Float;->floatToRawIntBits(F)I

    move-result v1

    cmpl-float v0, p0, v2

    if-lez v0, :cond_3

    const/4 v0, -0x1

    :goto_1
    add-int/2addr v0, v1

    invoke-static {v0}, Ljava/lang/Float;->intBitsToFloat(I)F

    move-result p0

    goto :goto_0

    :cond_3
    const/4 v0, 0x1

    goto :goto_1
.end method

.method public static nextUp(D)D
    .locals 6
    .parameter "d"

    .prologue
    const-wide/16 v4, 0x0

    .line 37
    invoke-static {p0, p1}, Ljava/lang/Double;->isNaN(D)Z

    move-result v0

    if-nez v0, :cond_0

    const-wide/high16 v0, 0x7ff0

    cmpl-double v0, p0, v0

    if-nez v0, :cond_1

    .line 41
    .end local p0
    :cond_0
    :goto_0
    return-wide p0

    .line 40
    .restart local p0
    :cond_1
    add-double/2addr p0, v4

    .line 41
    invoke-static {p0, p1}, Ljava/lang/Double;->doubleToRawLongBits(D)J

    move-result-wide v2

    cmpl-double v0, p0, v4

    if-ltz v0, :cond_2

    const/4 v0, 0x1

    :goto_1
    int-to-long v0, v0

    add-long/2addr v0, v2

    invoke-static {v0, v1}, Ljava/lang/Double;->longBitsToDouble(J)D

    move-result-wide p0

    goto :goto_0

    :cond_2
    const/4 v0, -0x1

    goto :goto_1
.end method

.method public static nextUpF(F)F
    .locals 3
    .parameter "f"

    .prologue
    const/4 v2, 0x0

    .line 10
    invoke-static {p0}, Ljava/lang/Float;->isNaN(F)Z

    move-result v0

    if-nez v0, :cond_0

    const/high16 v0, 0x7f80

    cmpl-float v0, p0, v0

    if-nez v0, :cond_1

    .line 14
    .end local p0
    :cond_0
    :goto_0
    return p0

    .line 13
    .restart local p0
    :cond_1
    add-float/2addr p0, v2

    .line 14
    invoke-static {p0}, Ljava/lang/Float;->floatToRawIntBits(F)I

    move-result v1

    cmpl-float v0, p0, v2

    if-ltz v0, :cond_2

    const/4 v0, 0x1

    :goto_1
    add-int/2addr v0, v1

    invoke-static {v0}, Ljava/lang/Float;->intBitsToFloat(I)F

    move-result p0

    goto :goto_0

    :cond_2
    const/4 v0, -0x1

    goto :goto_1
.end method

.method public static roundToOneSignificantFigure(D)F
    .locals 10
    .parameter "num"

    .prologue
    .line 85
    const-wide/16 v6, 0x0

    cmpg-double v3, p0, v6

    if-gez v3, :cond_0

    neg-double v6, p0

    :goto_0
    invoke-static {v6, v7}, Ljava/lang/Math;->log10(D)D

    move-result-wide v6

    double-to-float v3, v6

    float-to-double v6, v3

    invoke-static {v6, v7}, Ljava/lang/Math;->ceil(D)D

    move-result-wide v6

    double-to-float v0, v6

    .line 86
    .local v0, d:F
    float-to-int v3, v0

    rsub-int/lit8 v2, v3, 0x1

    .line 87
    .local v2, power:I
    const-wide/high16 v6, 0x4024

    int-to-double v8, v2

    invoke-static {v6, v7, v8, v9}, Ljava/lang/Math;->pow(DD)D

    move-result-wide v6

    double-to-float v1, v6

    .line 88
    .local v1, magnitude:F
    float-to-double v6, v1

    mul-double/2addr v6, p0

    invoke-static {v6, v7}, Ljava/lang/Math;->round(D)J

    move-result-wide v4

    .line 89
    .local v4, shifted:J
    long-to-float v3, v4

    div-float/2addr v3, v1

    return v3

    .end local v0           #d:F
    .end local v1           #magnitude:F
    .end local v2           #power:I
    .end local v4           #shifted:J
    :cond_0
    move-wide v6, p0

    .line 85
    goto :goto_0
.end method
